### ISSUE TITLE
LRC文件必须使用绝对地址，否则会报错

### ISSUE THREAD

**Issue by gu-fan** [MoePlayer/hexo-tag-aplayer#105]
````
{% aplayer "沉默是金" "张国荣" "/2021/09/20/embed-music/chenmoshijin.mp3"  "/2021/09/20/embed-music/chenmoshijin.jpg" "lrc:chenmoshijin.txt" %}
````

如题，只能使用相对地址，不过图片和歌曲都可以使用绝对地址。
这样的问题是就不能在其他文章中展示歌词

报错如下
```` javascript
TypeError: Cannot read property '_id' of undefined
    at APlayerTag.generate (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo-tag-aplayer/lib/tag/player.js:103:120)
    at Object.<anonymous> (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo-tag-aplayer/index.js:127:22)
    at NunjucksTag._run (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/extend/tag.js:57:20)
    at NunjucksTag.run (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/extend/tag.js:53:17)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/gu_fan/blog/gu-fan.github.io/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:8:67)
    at Template.render (/Users/gu_fan/blog/gu-fan.github.io/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/Users/gu_fan/blog/gu-fan.github.io/node_modules/nunjucks/src/environment.js:380:17)
    at /Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/extend/tag.js:236:16
    at tryCatcher (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/extend/tag.js:235:20)
    at Object.onRenderEnd (/Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/hexo/post.js:297:22)
    at /Users/gu_fan/blog/gu-fan.github.io/node_modules/hexo/lib/hexo/render.js:79:21
    at tryCatcher (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/gu_fan/blog/gu-fan.github.io/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
````

**Comment by App1ePine** [comment]
三年了没人解决吗，我也遇到了
