### ISSUE TITLE
hexo-tag-aplayer和gulp插件一起使用会报错

### ISSUE THREAD

**Issue by mapan2020** [MoePlayer/hexo-tag-aplayer#19]
[13:09:53] Using gulpfile D:\Blog\gulpfile.js
[13:09:53] Starting 'minify-html'...
[13:09:53] Starting 'minify-css'...
[13:09:53] Starting 'minify-js'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (D:\Blog\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at apply (D:\Blog\node_modules\lodash\_apply.js:16:25)
    at wrapper (D:\Blog\node_modules\lodash\_createCurry.js:41:12)
    at D:\Blog\node_modules\gulp-uglify\lib\minify.js:54:15
    at DestroyableTransform._transform (D:\Blog\node_modules\gulp-uglify\composer.js:10:23)
    at DestroyableTransform.Transform._read (D:\Blog\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (D:\Blog\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (D:\Blog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (D:\Blog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (D:\Blog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:322:11)

**Comment by mapan2020** [comment]
```\public\assets\js\APlayer.min.js```
此文件不能被gulp,会报错

**Comment by grzhan** [comment]
请问能提供有关的 gulp 脚本代码和插件版本信息吗？
----------------
Could you provide us more detailed information about your gulp scripts?

**Comment by mapan2020** [comment]
好吧，执行gulp时，我跳过了这个文件
```
gulp.task('minify-js', function() {
    return gulp.src(['./public/**/*.js','!./public/assets/js/*.js'])
        .pipe(uglify())
        .pipe(gulp.dest('./public'));
});
```

**Comment by mapan2020** [comment]
```
$ gulp -v
[14:55:13] CLI version 3.9.1
[14:55:13] Local version 3.9.1

```
