### ISSUE TITLE
关于引用后置资源文件夹的图片和lrc

### ISSUE THREAD

**Issue by chenjiageng** [MoePlayer/hexo-tag-aplayer#28]
我启用了后置资源文件夹，并且让它想作为图片和lrc储存。但是一直失败！望请赐教！
引用图片： ![](/jpg.jpg)  /  {％asset_img jpg.jpg %}
lrc如何引用？
以下是一部分报错文件
**如何正确引用lrc? 可否举个例子？**
``` bash
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: Specified music file not found {％asset_img meet.jpg ％}                                                  
    at Object.exports.prettifyError (/home/albert/blog/node_modules/nunjucks/src/lib.js:34:15)                     
    at /home/albert/blog/node_modules/nunjucks/src/environment.js:486:31                                           
    at new_cls.root [as rootRenderFunc] (eval at _compile (/home/albert/blog/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:18:3)                                                                                      
    at new_cls.render (/home/albert/blog/node_modules/nunjucks/src/environment.js:479:15)                          
    at new_cls.renderString (/home/albert/blog/node_modules/nunjucks/src/environment.js:327:21)                    
    at /home/albert/blog/node_modules/hexo/lib/extend/tag.js:66:9                                                  
    at Promise._execute (/home/albert/blog/node_modules/bluebird/js/release/debuggability.js:303:9)                
    at Promise._resolveFromExecutor (/home/albert/blog/node_modules/bluebird/js/release/promise.js:483:18)         
    at new Promise (/home/albert/blog/node_modules/bluebird/js/release/promise.js:79:10)                           
    at Tag.render (/home/albert/blog/node_modules/hexo/lib/extend/tag.js:64:10)                                    
    at Object.tagFilter [as onRenderEnd] (/home/albert/blog/node_modules/hexo/lib/hexo/post.js:266:16)             
    at /home/albert/blog/node_modules/hexo/lib/hexo/render.js:65:19                                                
    at tryCatcher (/home/albert/blog/node_modules/bluebird/js/release/util.js:16:23)                               
    at Promise._settlePromiseFromHandler (/home/albert/blog/node_modules/bluebird/js/release/promise.js:512:31)    
    at Promise._settlePromise (/home/albert/blog/node_modules/bluebird/js/release/promise.js:569:18)               
    at Promise._settlePromise0 (/home/albert/blog/node_modules/bluebird/js/release/promise.js:614:10)              
    at Promise._settlePromises (/home/albert/blog/node_modules/bluebird/js/release/promise.js:693:18)              
    at Async._drainQueue (/home/albert/blog/node_modules/bluebird/js/release/async.js:133:16)                      
    at Async._drainQueues (/home/albert/blog/node_modules/bluebird/js/release/async.js:143:10)                     
    at Immediate.Async.drainQueues (/home/albert/blog/node_modules/bluebird/js/release/async.js:17:14)             
    at runCallback (timers.js:773:18)                                                                              
    at tryOnImmediate (timers.js:734:5)                                                                            
    at processImmediate [as _immediateCallback] (timers.js:711:5)                                                  
```

**Comment by grzhan** [comment]
你好，开启 Hexo 的 `Post Asset Folder` 功能后，将歌词文件放到博客文章对应的资源文件夹（`Asset folder`），便可以直接利用 `{%aplayer %} ` 的 `lrc:xxx` 参数引用。

例如，我有一篇文章标题为 `foobar`，那么在对应目录就有个同名的`foobar`资源文件夹，将名为 `caffeine.txt` 的歌词文件放入，接下来就可以利用 `hexo-tag-aplayer` 直接引用该歌词文件：

```
{% aplayer "Caffeine" "Jeff Williams" "caffeine.mp3" "picture.jpg" "lrc:caffeine.txt" %}
```

详情可以参考 Hexo 官方文档：https://hexo.io/docs/asset-folders.html#Post-Asset-Folder

**Comment by chenjiageng** [comment]
@grzhan 非常感谢
