### ISSUE TITLE
图标巨大.....

### ISSUE THREAD

**Issue by wxlost** [MoePlayer/hexo-tag-aplayer#33]
刚刚用教程的命令安装的
└─┬ hexo-tag-dplayer@0.3.1
  ├── dplayer@1.22.2 deduped

http://111.230.103.51:4000/2018/03/12/love_music.html

![image](https://user-images.githubusercontent.com/19698455/37283114-cc60c512-2631-11e8-9ed4-5ee260e66c0a.png)
![image](https://user-images.githubusercontent.com/19698455/37283153-e115e7f8-2631-11e8-99db-b9be4a767f9b.png)

**Comment by Love4Taylor** [comment]
似乎是和 APlayer v1.7.0 的兼容问题, 换到 v1.6.0 则正常

**Comment by grzhan** [comment]
APlayer 1.7.0 开始需要引入额外的 CSS 文件。
在 `hexo-tag-aplayer@3.0.0` 版本中尝试修复，请看看还有没有问题（注意博客中的 APlayer 版本）

**Comment by wxlost** [comment]
@Love4Taylor 如何切换呢

**Comment by Love4Taylor** [comment]
@grzhan 3.0.0
hexo server -s 终端中无错误提示 网页内提示
`Error: [hexo-tag-aplayer] Specified asset file not found (undefined)`

hexo server 提示
```
Error: [hexo-tag-aplayer] Specified asset file not found (undefined)
    at throwError (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/common/util.js:18:9)
    at APlayerListTag.processUrl (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/base.js:43:40)
    at /home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:43:38
    at Array.forEach (<anonymous>)
    at APlayerListTag.parse (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:41:22)
    at new APlayerListTag (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:27:28)
    at Object.hexo.extend.tag.register.ends (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/index.js:148:15)
    at NunjucksBlock.NunjucksTag._run (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:120:18)
    at NunjucksBlock.run (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:144:15)
    at Template.root [as rootRenderFunc] (eval at _compile (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:9:71)
    at Template.render (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:540:10)
    at Environment.renderString (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:364:17)
    at Promise (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/home/love4taylor/Blog/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/love4taylor/Blog/node_modules/hexo/lib/hexo/post.js:260:16)
    at Promise.then.then.result (/home/love4taylor/Blog/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/love4taylor/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
```

**Comment by wxlost** [comment]
@Love4Taylor 
我安装3.0.0看list显示的是3.0.1.依然巨大图标..
hexo s --debug 启动正常

**Comment by grzhan** [comment]
@Love4Taylor 是重构过程中的 typo，请升级到 3.0.1 看看是否成功修复。

**Comment by wxlost** [comment]
@grzhan 您好.安装命令是`npm install --save hexo-tag-aplayer@3.0.1` 没错吧?

**Comment by Love4Taylor** [comment]
@grzhan 3.0.1
```
Error: [hexo-tag-aplayer] Specified asset file not found (cjeoyd7eo000a28u54mb6qg92)
    at throwError (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/common/util.js:18:9)
    at APlayerListTag.processUrl (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/base.js:43:40)
    at /home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:43:38
    at Array.forEach (<anonymous>)
    at APlayerListTag.parse (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:41:22)
    at new APlayerListTag (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/lib/tag/playerList.js:27:28)
    at Object.hexo.extend.tag.register.ends (/home/love4taylor/Blog/node_modules/hexo-tag-aplayer/index.js:148:15)
    at NunjucksBlock.NunjucksTag._run (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:120:18)
    at NunjucksBlock.run (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:144:15)
    at Template.root [as rootRenderFunc] (eval at _compile (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:9:71)
    at Template.render (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:540:10)
    at Environment.renderString (/home/love4taylor/Blog/node_modules/nunjucks/src/environment.js:364:17)
    at Promise (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/home/love4taylor/Blog/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/love4taylor/Blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/love4taylor/Blog/node_modules/hexo/lib/hexo/post.js:260:16)
    at Promise.then.then.result (/home/love4taylor/Blog/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/love4taylor/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/love4taylor/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/love4taylor/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
```

**Comment by wxlost** [comment]
@Love4Taylor 我刚重新安装了系统.然后安装了hexo和音乐插件...正常了....
http://111.230.103.51:4000/2018/03/12/love_music.html

**Comment by grzhan** [comment]
@Love4Taylor 方便的话看下 3.0.2 是否有问题

**Comment by Love4Taylor** [comment]
@grzhan 毒, 还是一样的问题
主题是: hexo-theme-material
Node: v9.8.0

**Comment by wxlost** [comment]
@grzhan 本地音乐不显示音乐长度是缺少什么插件没安装吗

**Comment by grzhan** [comment]
@Love4Taylor 请提供一下调用 tag 部分的原文，以及最新的错误信息

**Comment by grzhan** [comment]
@wxlost 可能是音乐文件本身的问题 （http://111.230.103.51:4000/2018/03/12/love_music/haicaowu.mp3）

**Comment by Love4Taylor** [comment]
@grzhan 刚才将 blog 整个重建了一边 似乎是正常了 试了几次生成和加载都没问题

**Comment by grzhan** [comment]
@Love4Taylor 好的，因为是重写后的版本，所以如果在使用中遇到什么问题请及时反馈
