### ISSUE TITLE
```hexo g``` error: value is not defined

### ISSUE THREAD

**Issue by kmahyyg** [MoePlayer/hexo-tag-aplayer#46]
```
INFO  Start processing
ReferenceError: value is not defined
    at /home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:92:88
    at Array.forEach (<anonymous>)
    at MetingTag.parse (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:47:20)
    at new MetingTag (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:31:28)
    at Object.<anonymous> (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo-tag-aplayer/index.js:162:15)
    at NunjucksTag._run (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/extend/tag.js:120:18)
    at NunjucksTag.run (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/extend/tag.js:116:15)
    at Template.root [as rootRenderFunc] (eval at _compile (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/nunjucks/src/environment.js:615:18), <anonymous>:9:66)
    at Template.render (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/nunjucks/src/environment.js:538:10)
    at Environment.renderString (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/nunjucks/src/environment.js:362:17)
    at Promise (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/hexo/post.js:230:16)
    at Promise.then.then.result (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/workspace/kmahyyg.github.io/blogrelease/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by kmahyyg** [comment]
This plugin is removed from my blog. I tried to use the officical netease music player HTML code.
