### ISSUE TITLE
无法正常使用Meting.js

### ISSUE THREAD

**Issue by idrey** [MoePlayer/hexo-tag-aplayer#72]
进行`hexo g`指令时出现以下错误信息，请问如何解决？
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 4]
  unknown block tag: meting
    at Object._prettifyError (C:\Users\idrey\hexo\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (C:\Users\idrey\hexo\node_modules\nunjucks\src\environment.js:542:21)
    at Environment.renderString (C:\Users\idrey\hexo\node_modules\nunjucks\src\environment.js:380:17)
    at Promise.fromCallback.cb (C:\Users\idrey\hexo\node_modules\hexo\lib\extend\tag.js:62:48)
    at tryCatcher (C:\Users\idrey\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\idrey\hexo\node_modules\bluebird\js\release\promise.js:180:30)
    at Tag.render (C:\Users\idrey\hexo\node_modules\hexo\lib\extend\tag.js:62:18)
    at Object.onRenderEnd (C:\Users\idrey\hexo\node_modules\hexo\lib\hexo\post.js:282:20)
    at Promise.then.then.result (C:\Users\idrey\hexo\node_modules\hexo\lib\hexo\render.js:65:19)
    at tryCatcher (C:\Users\idrey\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\idrey\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\idrey\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\idrey\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\idrey\hexo\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\idrey\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\idrey\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\idrey\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\idrey\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by whatqiu** [comment]
你标签没写好吧？我都一下就可以
https://whatqiu.github.io/2020/03/24/music/
