### ISSUE TITLE
请问这种错误如何解决？How to solve this kind of error?

### ISSUE THREAD

**Issue by Akijou-Lee** [MoePlayer/hexo-tag-aplayer#83]
##### 没有编程基础，看不懂也不知道该如何操作，在网上找了很多攻略也没有现成的答案，请求教导。感谢！ I really don't know how to read it or solve it since I am weak at learning programming. There is no answer to this kind of problem, I guest. Would you please help me? Thanks!
ERROR Render HTML failed: about/index.html
TypeError: Cannot read property 'includes' of null
    at PartialView.isFullPage (C:\Program Files\Hexo\blog\node_modules\hexo-tag-aplayer\lib\view.js:24:27)
    at Hexo.<anonymous> (C:\Program Files\Hexo\blog\node_modules\hexo-tag-aplayer\index.js:86:12)
    at Hexo.tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Program Files\Hexo\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by ghost** [comment]
me too
