### ISSUE TITLE
hexo g 时报错

### ISSUE THREAD

**Issue by Xcellerate** [MoePlayer/hexo-tag-aplayer#91]
> WARN  [hexo-tag-aplayer]: <head> not found in C:\...\themes\icarus\layout\page.jsx, unable to inject script (like 'APlayer.js') in this page
似乎会导致博客页面无法正常渲染，请问如何解决？

**Comment by young1lin** [comment]
我 `hexo g` 的时候报这个错误，我在 `switch` 前面声明了一个` var value = “”`；结果报另一个错误。我往上翻，发现 `value `竟然是个方法，还是个属性内部的方法。。。。
``` javascript
ReferenceError: value is not defined
    at /Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:120:100
    at Array.forEach (<anonymous>)
    at MetingTag.parse (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:75:26)
    at new MetingTag (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:59:32)
    at Object.<anonymous> (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/index.js:162:15)
    at NunjucksTag._run (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:170:18)
    at NunjucksTag.run (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:166:15)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:8:66)
    at Template.render (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:550:10)
    at Environment.renderString (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:378:17)
    at /Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:120:48
    at tryCatcher (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:120:18)
    at Object.onRenderEnd (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/hexo/post.js:291:22)
    at /Users/linyoung/Blog/blog-final/node_modules/hexo/lib/hexo/render.js:79:21
    at tryCatcher (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
ReferenceError: value is not defined
    at /Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:120:100
    at Array.forEach (<anonymous>)
    at MetingTag.parse (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:75:26)
    at new MetingTag (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/lib/tag/playerMeting.js:59:32)
    at Object.<anonymous> (/Users/linyoung/Blog/blog-final/node_modules/hexo-tag-aplayer/index.js:162:15)
    at NunjucksTag._run (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:170:18)
    at NunjucksTag.run (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:166:15)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:8:66)
    at Template.render (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:550:10)
    at Environment.renderString (/Users/linyoung/Blog/blog-final/node_modules/nunjucks/src/environment.js:378:17)
    at /Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:120:48
    at tryCatcher (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/extend/tag.js:120:18)
    at Object.onRenderEnd (/Users/linyoung/Blog/blog-final/node_modules/hexo/lib/hexo/post.js:291:22)
    at /Users/linyoung/Blog/blog-final/node_modules/hexo/lib/hexo/render.js:79:21
    at tryCatcher (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/linyoung/Blog/blog-final/node_modules/bluebird/js/release/async.js:15:14)
```
